import type { CollectionConfig } from 'payload'

export const Media: CollectionConfig = {
  slug: 'media',
  access: {
    read: () => true,
  },
  fields: [
    {
      // WORKAROUND: Custom UUID field for manual ID generation
      // See WORKAROUND-UUID.md for full explanation
      // UUIDs must be generated in API routes before calling payload.create()
      name: 'id',
      type: 'text',
      required: false, // Optional to allow Admin UI uploads without UUIDs (for now)
      admin: {
        hidden: true, // Hidden from Admin UI
        description: 'UUID generated by API routes or custom component',
      },
      // NOTE: NO HOOKS - they break in Cloudflare Workers!
      // Do not add: hooks: { beforeValidate: [...] }
      // NOTE: Custom React component removed due to TypeScript compatibility issues
      // Will be re-added once we have working examples from payload-d1
    },
    {
      name: 'alt',
      type: 'text',
      required: true,
    },
  ],
  upload: {
    // These are not supported on Workers yet due to lack of sharp
    crop: false,
    focalPoint: false,
  },
}
